### ISSUE TITLE
How to use neon-wallet-db with private db?

### ISSUE THREAD

**Issue by blueplanet** [CityOfZion/light-wallet-db#12]
Hi everybody, Please help me out.

I tried connect to private net, but follwing error:

```
16:04:53 clock.1    |  Traceback (most recent call last):
16:04:53 clock.1    |    File "/Users/gyo/.anyenv/envs/pyenv/versions/3.6.5/lib/python3.6/site-packages/apscheduler/executors/base.py", line 125, in run_job
16:04:53 clock.1    |      retval = job.func(*job.args, **job.kwargs)
16:04:53 clock.1    |    File "clock.py", line 24, in syncBlockchain
16:04:53 clock.1    |      currBlock = getBlockCount(nodeAPI)["result"]
16:04:53 clock.1    |    File "/Users/gyo/dev/neo-hack/neon-wallet-db/api/blockchain.py", line 28, in getBlockCount
16:04:53 clock.1    |      return rpcRequest("getblockcount", [], nodeAPI)
16:04:53 clock.1    |    File "/Users/gyo/dev/neo-hack/neon-wallet-db/api/blockchain.py", line 17, in rpcRequest
16:04:53 clock.1    |      return requests.post(nodeAPI, json={"jsonrpc": "2.0", "method": method, "params": params, "id": 0}, timeout=5).json()
16:04:53 clock.1    |    File "/Users/gyo/.anyenv/envs/pyenv/versions/3.6.5/lib/python3.6/site-packages/requests/api.py", line 112, in post
16:04:53 clock.1    |      return request('post', url, data=data, json=json, **kwargs)
16:04:53 clock.1    |    File "/Users/gyo/.anyenv/envs/pyenv/versions/3.6.5/lib/python3.6/site-packages/requests/api.py", line 58, in request
16:04:53 clock.1    |      return session.request(method=method, url=url, **kwargs)
16:04:53 clock.1    |    File "/Users/gyo/.anyenv/envs/pyenv/versions/3.6.5/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
16:04:53 clock.1    |      resp = self.send(prep, **send_kwargs)
16:04:53 clock.1    |    File "/Users/gyo/.anyenv/envs/pyenv/versions/3.6.5/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
16:04:53 clock.1    |      r = adapter.send(request, **kwargs)
16:04:53 clock.1    |    File "/Users/gyo/.anyenv/envs/pyenv/versions/3.6.5/lib/python3.6/site-packages/requests/adapters.py", line 490, in send
16:04:53 clock.1    |      raise ConnectionError(err, request=request)
16:04:53 clock.1    |  requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("±Ý\x00\x00version\x00\x00\x00\x00\x00'\x00\x00\x00\x9e+\x96\x87\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00<¿ÉZmOÜÓ\x0c \x0b/NEO:2.7.3/\x8cN\x00\x00\x01",))
```

## My env

```javascript
# install neo-privatenet-docker, neo-python and run it,  and, curl is successed.
$ curl -X POST http://127.0.0.1:20332 -d '{"jsonrpc":"2.0","method":"getblockcount", "id":1}'
{"jsonrpc": "2.0", "id": 1, "result": 464}
```

**Comment by DNK90** [comment]
Hi @blueplanet 
you can see my pull request:
https://github.com/CityOfZion/neon-wallet-db/pull/13

Plus, you can see the instruction on how to work with private network here:
https://github.com/DNK90/neosample
